### ISSUE TITLE
Migrate directory to ember-cli

### ISSUE THREAD

**Issue by karlfreeman** [middleman/middleman-directory#107]
So much great work has been done by team @thoughtbot on the redesign of Middleman. Haven taken a step away from OS work it's been lovely to see how much slicker Middleman looks (It's allways been slick on the inside :wink:).

![screen shot 2015-02-17 at 13 41 11](https://cloud.githubusercontent.com/assets/139095/6229231/3adabcde-b6ad-11e4-9345-84b2c8a9ed46.png)

When the initial [emberization](https://github.com/middleman/middleman-directory/commit/b106b0214d88025ea796adb6ecfbdee18f30584f) happened @ember-cli wasn't as prevalently used. Now on the other hand, if you're building an ember application you would be mad not too use it. Especially a project such as this one.

I believe ember-cli'ing the directory would open the door to more contributions and additionally allow us to play around with new features.

How does moving the directory over to ember-cli sound?

_we would still continue to deploy with the fine folks over at @divshot_

**Comment by tdreyno** [comment]
I would love this. It would also make a nice testbed for v4's external tooling support.

cc @tysongach in case he has any thoughts on the design of the directory
