### ISSUE TITLE
Merge "built with" into the directory

### ISSUE THREAD

**Issue by karlfreeman** [middleman/middleman-directory#108]
I wonder if we could reduce the [churn on middleman-guides](https://github.com/middleman/middleman-guides/commits/master/data/sites.yml) by trying to merge the ["built with"](https://middlemanapp.com/community/built_using_middleman/) section away. Also, if people like the sound of #107 it would allow us to have one central place for [trivial yml pull requests](https://github.com/middleman/middleman-guides/pulls?q=is%3Apr+is%3Aclosed+%26+sites.yml) and most likely the ability to share some functionality to show off the middleman community.

**Comment by tdreyno** [comment]
I like it. I don't mind the churn and like to encourage folks to "say hi" with a PR. But the directory does seem like a better home,
