### ISSUE TITLE
Generated tags list has duplicates

### ISSUE THREAD

**Issue by pzi** [middleman/middleman-directory#125]
Hello

I was looking at why there are duplicates in the tags list at the top of the directory. Especially in the templates section there are many of them.

The problem I found was that the use of the Ember `uniq` method does not work as intended.

It does a string comparison, however due to it's case-sensitivity it fails at eliminating dupes. Best example is the 'CoffeeScript' tag. [Quick example using Lo-Dash](https://jsfiddle.net/hgdyLet0/).

I didn't have the time this morning to have a look if a newer version of Ember would fix the problem or if there would have to be some different/new approach of creating the tag collection altogether, similar to what is in the JSFiddle above.

However, having little to no experience with Ember, is that actually something that'd be considered by you, to update Ember?

Thanks & Cheers
Patrik

**Comment by tdreyno** [comment]
Good catch. I think we just need to downcase the tags before uniq.

**Comment by pzi** [comment]
Yeah, that's what I thought might be the best option. For now, I was cleaning up `templates.yml`. Will have time again in about an hour and will put up a PR with a cleaned up version. The lowercasing alone will not solve it 100% as it does not cater for things like "ZURB Foundation" vs. "Foundation".
